import { FeedWrapper } from "@/components/feed-wrapper";
import { StickyWrapper } from "@/components/sticky-wrapper";
import { UserProgress } from "@/components/user-progress";
import { Quests } from "@/components/quests";
import { Feedback } from "@/components/Feedback";
import { RegionImage } from "@/components/current_region_image";
import { FlashcardsPracticeClient } from "./FlashcardsClient";
import { getUserProgress } from "@/db/queries";

const flashcards = [
  {
    id: 1,
    word: "Бульба",
    translation_ua: "картопля",
    translation_en: "potato",
    translation_de: "Kartoffel",
    audioSrc: "/audio/7/Бульба.mp3",
  },
  {
    id: 2,
    word: "Лєс",
    translation_ua: "ліс",
    translation_en: "forest",
    translation_de: "Wald",
    audioSrc: "/audio/7/Лєс.mp3",
  },
  {
    id: 3,
    word: "Гуторити",
    translation_ua: "розмовляти",
    translation_en: "to talk",
    translation_de: "sprechen",
    audioSrc: "/audio/7/Гуторити.mp3",
  },
  {
    id: 4,
    word: "Куфер",
    translation_ua: "валіза, скриня",
    translation_en: "trunk, chest",
    translation_de: "Koffer, Truhe",
    audioSrc: "/audio/7/Куфер.mp3",
  },
  {
    id: 5,
    word: "Припічок",
    translation_ua: "місце біля печі",
    translation_en: "place near the stove",
    translation_de: "Platz neben dem Herd",
    audioSrc: "/audio/7/Припічок.mp3",
  },
  {
    id: 6,
    word: "Клюмба",
    translation_ua: "квітник",
    translation_en: "flowerbed",
    translation_de: "Blumenbeet",
    audioSrc: "/audio/7/Клюмба.mp3",
  },
  {
    id: 7,
    word: "Порєдок",
    translation_ua: "порядок",
    translation_en: "order",
    translation_de: "Ordnung",
    audioSrc: "/audio/7/Порєдок.mp3",
  },
  {
    id: 8,
    word: "Лєснік",
    translation_ua: "лісник",
    translation_en: "forester",
    translation_de: "Förster",
    audioSrc: "/audio/7/Лєснік.mp3",
  },
  {
    id: 9,
    word: "Прип’ятник",
    translation_ua: "камінь-пам’ятник",
    translation_en: "memorial stone",
    translation_de: "Gedenkstein",
    audioSrc: "/audio/7/Прип’ятник.mp3",
  },
  {
    id: 10,
    word: "Клямка",
    translation_ua: "дверна ручка",
    translation_en: "door handle",
    translation_de: "Türgriff",
    audioSrc: "/audio/7/Клямка.mp3",
  },
  {
    id: 11,
    word: "Шчьо",
    translation_ua: "що",
    translation_en: "what",
    translation_de: "was",
    audioSrc: "/audio/7/Шчьо.mp3",
  },
  {
    id: 12,
    word: "Хвіртка",
    translation_ua: "брама, ворота",
    translation_en: "gate, doorway",
    translation_de: "Tor, Pforte",
    audioSrc: "/audio/7/Хвіртка.mp3",
  },
  {
    id: 13,
    word: "Погрєб",
    translation_ua: "льох",
    translation_en: "cellar",
    translation_de: "Keller",
    audioSrc: "/audio/7/Погрєб.mp3",
  },
  {
    id: 14,
    word: "Калачі",
    translation_ua: "хлібці з білого тіста",
    translation_en: "white bread rolls",
    translation_de: "Weißbrotbrötchen",
    audioSrc: "/audio/7/Калачі.mp3",
  },
  {
    id: 15,
    word: "Шопка",
    translation_ua: "невеликий сарай",
    translation_en: "small shed",
    translation_de: "kleiner Schuppen",
    audioSrc: "/audio/7/Шопка.mp3",
  },
  {
    id: 16,
    word: "Посьолок",
    translation_ua: "селище",
    translation_en: "settlement",
    translation_de: "Siedlung",
    audioSrc: "/audio/7/Посьолок.mp3",
  },
  {
    id: 17,
    word: "Дєдьо",
    translation_ua: "дядько",
    translation_en: "uncle",
    translation_de: "Onkel",
    audioSrc: "/audio/7/Дєдьо.mp3",
  },

  // ===== table 8 =====
  {
    id: 101,
    word: "Ґазда",
    translation_ua: "господар",
    translation_en: "master, host",
    translation_de: "Hausherr",
    audioSrc: "/audio/8/газда.mp3",
  },
  {
    id: 102,
    word: "Файний",
    translation_ua: "гарний",
    translation_en: "nice, good",
    translation_de: "schön, gut",
    audioSrc: "/audio/8/файний.mp3",
  },
  {
    id: 103,
    word: "ґринджоли",
    translation_ua: "санчата",
    translation_en: "sleds",
    translation_de: "Schlitten",
    audioSrc: "/audio/8/ґринджоли.mp3",
  },
  {
    id: 104,
    word: "Леванда",
    translation_ua: "підлога",
    translation_en: "floor",
    translation_de: "Boden",
    audioSrc: "/audio/8/леванда.mp3",
  },
  {
    id: 105,
    word: "Мешти",
    translation_ua: "взуття",
    translation_en: "shoes",
    translation_de: "Schuhe",
    audioSrc: "/audio/8/мешти.mp3",
  },
  {
    id: 106,
    word: "Плай",
    translation_ua: "гірська стежка",
    translation_en: "mountain path",
    translation_de: "Bergpfad",
    audioSrc: "/audio/8/плай.mp3",
  },
  {
    id: 107,
    word: "Кучма",
    translation_ua: "тепла шапка",
    translation_en: "warm hat",
    translation_de: "warme Mütze",
    audioSrc: "/audio/8/кучма.mp3",
  },
  {
    id: 108,
    word: "Фіртка",
    translation_ua: "хвіртка",
    translation_en: "small gate",
    translation_de: "kleines Tor",
    audioSrc: "/audio/8/фіртка.mp3",
  },
  {
    id: 109,
    word: "Плєцак",
    translation_ua: "рюкзак",
    translation_en: "backpack",
    translation_de: "Rucksack",
    audioSrc: "/audio/8/плєцак.mp3",
  },
  {
    id: 110,
    word: "Баняк",
    translation_ua: "каструля",
    translation_en: "pot, saucepan",
    translation_de: "Topf",
    audioSrc: "/audio/8/баняк.mp3",
  },
  {
    id: 111,
    word: "Ліґуміна",
    translation_ua: "солодка страва, десерт",
    translation_en: "sweet dish, dessert",
    translation_de: "süße Speise, Dessert",
    audioSrc: "/audio/8/ліґуміна.mp3",
  },
  {
    id: 112,
    word: "Ґейби",
    translation_ua: "начебто, ніби",
    translation_en: "as if",
    translation_de: "als ob",
    audioSrc: "/audio/8/Ґейби.mp3",
  },
  {
    id: 113,
    word: "Бляшняр",
    translation_ua: "майстер, що працює з бляхою",
    translation_en: "metal worker",
    translation_de: "Blechner",
    audioSrc: "/audio/8/Бляшняр.mp3",
  },
  {
    id: 114,
    word: "Позір",
    translation_ua: "увага",
    translation_en: "attention",
    translation_de: "Aufmerksamkeit",
    audioSrc: "/audio/8/Позір.mp3",
  },
  {
    id: 115,
    word: "Стодоля",
    translation_ua: "комора для зерна",
    translation_en: "grain storage, barn",
    translation_de: "Getreidespeicher, Scheune",
    audioSrc: "/audio/8/Стодоля.mp3",
  },
  {
    id: 116,
    word: "Кужіль",
    translation_ua: "прядиво, волокно льону чи конопель",
    translation_en: "fiber, flax or hemp",
    translation_de: "Faser, Leinen- oder Hanffaser",
    audioSrc: "/audio/8/Кужіль.mp3",
  },
  {
    id: 117,
    word: "Гвер",
    translation_ua: "рушниця",
    translation_en: "rifle",
    translation_de: "Gewehr",
    audioSrc: "/audio/8/Гвер.mp3",
  },
  {
    id: 118,
    word: "Пляц",
    translation_ua: "земельна ділянка",
    translation_en: "plot of land",
    translation_de: "Grundstück",
    audioSrc: "/audio/8/Пляц.mp3",
  },

  // ===== table 9 =====
  {
    id: 201,
    word: "Пшонка",
    translation_ua: "кукурудза",
    translation_en: "corn",
    translation_de: "Mais",
    audioSrc: "/audio/9/Пшонка.mp3",
  },
  {
    id: 202,
    word: "Поребрик",
    translation_ua: "бордюр",
    translation_en: "curb",
    translation_de: "Bordstein",
    audioSrc: "/audio/9/Поребрик.mp3",
  },
  {
    id: 203,
    word: "Кабанчик",
    translation_ua: "свиня",
    translation_en: "piglet",
    translation_de: "Ferkel",
    audioSrc: "/audio/9/Кабанчик.mp3",
  },
  {
    id: 204,
    word: "Калач",
    translation_ua: "круглий хлібний витвір",
    translation_en: "round bread",
    translation_de: "rundes Brotgebäck",
    audioSrc: "/audio/9/Калач.mp3",
  },
  {
    id: 205,
    word: "Хата",
    translation_ua: "житловий будинок",
    translation_en: "house",
    translation_de: "Wohnhaus",
    audioSrc: "/audio/9/Хата.mp3",
  },
  {
    id: 206,
    word: "Шаньга",
    translation_ua: "круглий пиріг",
    translation_en: "round pie",
    translation_de: "runder Kuchen",
    audioSrc: "/audio/9/Шаньга.mp3",
  },
  {
    id: 207,
    word: "Ненька",
    translation_ua: "колиска",
    translation_en: "cradle",
    translation_de: "Wiege",
    audioSrc: "/audio/9/Ненька.mp3",
  },
  {
    id: 208,
    word: "Веселуха",
    translation_ua: "райдуга",
    translation_en: "rainbow",
    translation_de: "Regenbogen",
    audioSrc: "/audio/9/Веселуха.mp3",
  },
  {
    id: 209,
    word: "Билиця",
    translation_ua: "білка",
    translation_en: "squirrel",
    translation_de: "Eichhörnchen",
    audioSrc: "/audio/9/Билиця.mp3",
  },
  {
    id: 210,
    word: "Змійка",
    translation_ua: "блискавка",
    translation_en: "zipper",
    translation_de: "Reißverschluss",
    audioSrc: "/audio/9/Змійка.mp3",
  },
  {
    id: 211,
    word: "Синеньки",
    translation_ua: "баклажани",
    translation_en: "eggplants",
    translation_de: "Auberginen",
    audioSrc: "/audio/9/Синеньки.mp3",
  },
  {
    key: "10-1",
    region: 10,
    id: 1,
    word: "ik",
    translation_ua: "я",
    translation_en: "I",
    translation_de: "ich",
    audioSrc: "/audio/10/ik.mp3",
  },
  {
    key: "10-2",
    region: 10,
    id: 2,
    word: "du",
    translation_ua: "ти",
    translation_en: "you",
    translation_de: "du",
    audioSrc: "/audio/10/du.mp3",
  },
  {
    key: "10-3",
    region: 10,
    id: 3,
    word: "he",
    translation_ua: "він",
    translation_en: "he",
    translation_de: "er",
    audioSrc: "/audio/10/he.mp3",
  },
  {
    key: "10-4",
    region: 10,
    id: 4,
    word: "wu / wie",
    translation_ua: "ми",
    translation_en: "we",
    translation_de: "wir",
    audioSrc: "/audio/10/wi.mp3",
  },
  {
    key: "10-5",
    region: 10,
    id: 5,
    word: "se",
    translation_ua: "вони",
    translation_en: "they",
    translation_de: "sie",
    audioSrc: "/audio/10/se.mp3",
  },
  {
    key: "10-6",
    region: 10,
    id: 6,
    word: "maken",
    translation_ua: "робити",
    translation_en: "to do / make",
    translation_de: "machen",
    audioSrc: "/audio/10/maken.mp3",
  },
  {
    key: "10-8",
    region: 10,
    id: 8,
    word: "doon",
    translation_ua: "робити (platt)",
    translation_en: "to do (platt)",
    translation_de: "machen",
    audioSrc: "/audio/10/doon.mp3",
  },
  {
    key: "10-9",
    region: 10,
    id: 9,
    word: "gahn",
    translation_ua: "йти",
    translation_en: "to go",
    translation_de: "gehen",
    audioSrc: "/audio/10/gahn.mp3",
  },
  {
    key: "10-10",
    region: 10,
    id: 10,
    word: "kömen",
    translation_ua: "приходити",
    translation_en: "to come",
    translation_de: "kommen",
    audioSrc: "/audio/10/komen.mp3",
  },
  {
    key: "10-11",
    region: 10,
    id: 11,
    word: "spreken",
    translation_ua: "говорити",
    translation_en: "to speak",
    translation_de: "sprechen",
    audioSrc: "/audio/10/spreken.mp3",
  },
  {
    key: "10-12",
    region: 10,
    id: 12,
    word: "verstahn",
    translation_ua: "розуміти",
    translation_en: "to understand",
    translation_de: "verstehen",
    audioSrc: "/audio/10/verstahn.mp3",
  },
  {
    key: "10-13",
    region: 10,
    id: 13,
    word: "hewwen",
    translation_ua: "мати",
    translation_en: "to have",
    translation_de: "haben",
    audioSrc: "/audio/10/hewwen.mp3",
  },
  {
    key: "10-14",
    region: 10,
    id: 14,
    word: "Bröödt / Brood",
    translation_ua: "хліб",
    translation_en: "bread",
    translation_de: "Brot",
    audioSrc: "/audio/10/Broodt  Brood.mp3",
  },
  {
    key: "10-15",
    region: 10,
    id: 15,
    word: "Water",
    translation_ua: "вода",
    translation_en: "water",
    translation_de: "Wasser",
    audioSrc: "/audio/10/water.mp3",
  },
  {
    key: "10-16",
    region: 10,
    id: 16,
    word: "Melk",
    translation_ua: "молоко",
    translation_en: "milk",
    translation_de: "Milch",
    audioSrc: "/audio/10/melk.mp3",
  },
  {
    key: "10-17",
    region: 10,
    id: 17,
    word: "Koffie",
    translation_ua: "кава",
    translation_en: "coffee",
    translation_de: "Kaffee",
    audioSrc: "/audio/10/koffie.mp3",
  },
  {
    key: "10-18",
    region: 10,
    id: 18,
    word: "Tee",
    translation_ua: "чай",
    translation_en: "tea",
    translation_de: "Tee",
    audioSrc: "/audio/10/tee.mp3",
  },
  {
    key: "10-19",
    region: 10,
    id: 19,
    word: "Eten",
    translation_ua: "їсти",
    translation_en: "to eat",
    translation_de: "essen",
    audioSrc: "/audio/10/eten.mp3",
  },
  {
    key: "10-20",
    region: 10,
    id: 20,
    word: "Drinke",
    translation_ua: "пити",
    translation_en: "to drink",
    translation_de: "trinken",
    audioSrc: "/audio/10/drinke.mp3",
  },
  {
    key: "10-21",
    region: 10,
    id: 21,
    word: "Appel",
    translation_ua: "яблуко",
    translation_en: "apple",
    translation_de: "Apfel",
    audioSrc: "/audio/10/appel.mp3",
  },
  {
    key: "10-22",
    region: 10,
    id: 22,
    word: "Koken",
    translation_ua: "готувати",
    translation_en: "to cook",
    translation_de: "kochen",
    audioSrc: "/audio/10/koken.mp3",
  },
  {
    key: "10-23",
    region: 10,
    id: 23,
    word: "Moin!",
    translation_ua: "привіт",
    translation_en: "hello",
    translation_de: "Hallo",
    audioSrc: "/audio/10/moin!.mp3",
  },
  {
    key: "10-24",
    region: 10,
    id: 24,
    word: "Aben!",
    translation_ua: "добрий вечір",
    translation_en: "good evening",
    translation_de: "Guten Abend",
    audioSrc: "/audio/10/aben!.mp3",
  },
  {
    key: "10-25",
    region: 10,
    id: 25,
    word: "vadder",
    translation_ua: "батько",
    translation_en: "father",
    translation_de: "Vater",
    audioSrc: "/audio/10/vadder.mp3",
  },
  {
    key: "10-26",
    region: 10,
    id: 26,
    word: "Moder",
    translation_ua: "мати",
    translation_en: "mother",
    translation_de: "Mutter",
    audioSrc: "/audio/10/moder.mp3",
  },
  {
    key: "10-27",
    region: 10,
    id: 27,
    word: "Kinner",
    translation_ua: "діти",
    translation_en: "children",
    translation_de: "Kinder",
    audioSrc: "/audio/10/kinner.mp3",
  },
  {
    key: "10-28",
    region: 10,
    id: 28,
    word: "Broder",
    translation_ua: "брат",
    translation_en: "brother",
    translation_de: "Bruder",
    audioSrc: "/audio/10/broder.mp3",
  },
  {
    key: "10-29",
    region: 10,
    id: 29,
    word: "Süster",
    translation_ua: "сестра",
    translation_en: "sister",
    translation_de: "Schwester",
    audioSrc: "/audio/10/suster.mp3",
  },
  {
    key: "10-30",
    region: 10,
    id: 30,
    word: "Oma",
    translation_ua: "бабуся",
    translation_en: "grandmother",
    translation_de: "Großmutter",
    audioSrc: "/audio/10/oma.mp3",
  },
  {
    key: "10-31",
    region: 10,
    id: 31,
    word: "Opa",
    translation_ua: "дідусь",
    translation_en: "grandfather",
    translation_de: "Großvater",
    audioSrc: "/audio/10/opa.mp3",
  },
  {
    key: "10-32",
    region: 10,
    id: 32,
    word: "Mien",
    translation_ua: "мій",
    translation_en: "my",
    translation_de: "mein",
    audioSrc: "/audio/10/mien.mp3",
  },
  {
    key: "10-33",
    region: 10,
    id: 33,
    word: "Dien",
    translation_ua: "твій",
    translation_en: "your",
    translation_de: "dein",
    audioSrc: "/audio/10/dien.mp3",
  },
  {
    key: "10-34",
    region: 10,
    id: 34,
    word: "ehr",
    translation_ua: "її",
    translation_en: "her",
    translation_de: "ihr",
    audioSrc: "/audio/10/ehr.mp3",
  },
  {
    key: "10-35",
    region: 10,
    id: 35,
    word: "sien",
    translation_ua: "його",
    translation_en: "his",
    translation_de: "sein",
    audioSrc: "/audio/10/sien.mp3",
  },
  {
    key: "10-36",
    region: 10,
    id: 36,
    word: "huus",
    translation_ua: "дім",
    translation_en: "house",
    translation_de: "Haus",
    audioSrc: "/audio/10/huus.mp3",
  },
  {
    key: "10-37",
    region: 10,
    id: 37,
    word: "fenster",
    translation_ua: "вікно",
    translation_en: "window",
    translation_de: "Fenster",
    audioSrc: "/audio/10/fenster.mp3",
  },
  {
    key: "10-38",
    region: 10,
    id: 38,
    word: "kammer",
    translation_ua: "кімната",
    translation_en: "room",
    translation_de: "Zimmer",
    audioSrc: "/audio/10/kammer.mp3",
  },
  {
    key: "10-39",
    region: 10,
    id: 39,
    word: "stuw",
    translation_ua: "вітальня",
    translation_en: "living room",
    translation_de: "Wohnzimmer",
    audioSrc: "/audio/10/stuw.mp3",
  },
  {
    key: "10-40",
    region: 10,
    id: 40,
    word: "Kök",
    translation_ua: "кухня",
    translation_en: "kitchen",
    translation_de: "Küche",
    audioSrc: "/audio/10/kok.mp3",
  },
  {
    key: "10-41",
    region: 10,
    id: 41,
    word: "Tied",
    translation_ua: "час",
    translation_en: "time",
    translation_de: "Zeit",
    audioSrc: "/audio/10/tied.mp3",
  },
  {
    key: "10-42",
    region: 10,
    id: 42,
    word: "Keen",
    translation_ua: "жоден / нема",
    translation_en: "none",
    translation_de: "keiner",
    audioSrc: "/audio/10/keen.mp3",
  },
  {
    key: "10-43",
    region: 10,
    id: 43,
    word: "Schoul",
    translation_ua: "школа",
    translation_en: "school",
    translation_de: "Schule",
    audioSrc: "/audio/10/schoul.mp3",
  },
  {
    key: "10-44",
    region: 10,
    id: 44,
    word: "Leter",
    translation_ua: "вчитель",
    translation_en: "teacher",
    translation_de: "Lehrer",
    audioSrc: "/audio/10/leter.mp3",
  },
  {
    key: "10-45",
    region: 10,
    id: 45,
    word: "Schöler",
    translation_ua: "учень",
    translation_en: "pupil",
    translation_de: "Schüler",
    audioSrc: "/audio/10/scholer.mp3",
  },
  {
    key: "10-46",
    region: 10,
    id: 46,
    word: "Leren",
    translation_ua: "вчитися",
    translation_en: "to learn",
    translation_de: "lernen",
    audioSrc: "/audio/10/leren.mp3",
  },
  {
    key: "10-47",
    region: 10,
    id: 47,
    word: "Schrieven",
    translation_ua: "писати",
    translation_en: "to write",
    translation_de: "schreiben",
    audioSrc: "/audio/10/Schrieven.mp3",
  },
  {
    key: "10-48",
    region: 10,
    id: 48,
    word: "Lesen",
    translation_ua: "читати",
    translation_en: "to read",
    translation_de: "lesen",
    audioSrc: "/audio/10/lesen.mp3",
  },
  {
    key: "10-49",
    region: 10,
    id: 49,
    word: "klass",
    translation_ua: "клас",
    translation_en: "class",
    translation_de: "Klasse",
    audioSrc: "/audio/10/Klass.mp3",
  },
  {
    key: "11-1",
    region: 11,
    id: 1,
    word: "Isch",
    translation_ua: "я",
    translation_en: "I",
    translation_de: "ich",
    audioSrc: "/audio/11/isch.mp3",
  },
  {
    key: "11-2",
    region: 11,
    id: 2,
    word: "du",
    translation_ua: "ти",
    translation_en: "you",
    translation_de: "du",
    audioSrc: "/audio/11/du.mp3",
  },
  {
    key: "11-3",
    region: 11,
    id: 3,
    word: "är",
    translation_ua: "він",
    translation_en: "he",
    translation_de: "er",
    audioSrc: "/audio/11/ar.mp3",
  },
  {
    key: "11-4",
    region: 11,
    id: 4,
    word: "mir",
    translation_ua: "ми",
    translation_en: "we",
    translation_de: "wir",
    audioSrc: "/audio/11/mir.mp3",
  },
  {
    key: "11-5",
    region: 11,
    id: 5,
    word: "si",
    translation_ua: "вони",
    translation_en: "they",
    translation_de: "sie",
    audioSrc: "/audio/11/si.mp3",
  },
  {
    key: "11-6",
    region: 11,
    id: 6,
    word: "macha",
    translation_ua: "робити",
    translation_en: "to do / make",
    translation_de: "machen",
    audioSrc: "/audio/11/macha.mp3",
  },
  {
    key: "11-7",
    region: 11,
    id: 7,
    word: "ganga",
    translation_ua: "йти",
    translation_en: "to go",
    translation_de: "gehen",
    audioSrc: "/audio/11/ganga.mp3",
  },
  {
    key: "11-8",
    region: 11,
    id: 8,
    word: "kema",
    translation_ua: "приходити",
    translation_en: "to come",
    translation_de: "kommen",
    audioSrc: "/audio/11/kema.mp3",
  },
  {
    key: "11-9",
    region: 11,
    id: 9,
    word: "reda",
    translation_ua: "говорити",
    translation_en: "to speak",
    translation_de: "sprechen",
    audioSrc: "/audio/11/reda.mp3",
  },
  {
    key: "11-10",
    region: 11,
    id: 10,
    word: "vaschtaa",
    translation_ua: "розуміти",
    translation_en: "to understand",
    translation_de: "verstehen",
    audioSrc: "/audio/11/vaschtaa.mp3",
  },
  {
    key: "11-11",
    region: 11,
    id: 11,
    word: "ha",
    translation_ua: "мати",
    translation_en: "to have",
    translation_de: "haben",
    audioSrc: "/audio/11/ha.mp3",
  },
  {
    key: "11-12",
    region: 11,
    id: 12,
    word: "Brot",
    translation_ua: "хліб",
    translation_en: "bread",
    translation_de: "Brot",
    audioSrc: "/audio/11/brot.mp3",
  },
  {
    key: "11-13",
    region: 11,
    id: 13,
    word: "Wossa",
    translation_ua: "вода",
    translation_en: "water",
    translation_de: "Wasser",
    audioSrc: "/audio/11/wossa.mp3",
  },
  {
    key: "11-14",
    region: 11,
    id: 14,
    word: "Milch",
    translation_ua: "молоко",
    translation_en: "milk",
    translation_de: "Milch",
    audioSrc: "/audio/11/milch.mp3",
  },
  {
    key: "11-15",
    region: 11,
    id: 15,
    word: "Kaffee",
    translation_ua: "кава",
    translation_en: "coffee",
    translation_de: "Kaffee",
    audioSrc: "/audio/11/kaffee.mp3",
  },
  {
    key: "11-16",
    region: 11,
    id: 16,
    word: "Tee",
    translation_ua: "чай",
    translation_en: "tea",
    translation_de: "Tee",
    audioSrc: "/audio/11/tee.mp3",
  },
  {
    key: "11-17",
    region: 11,
    id: 17,
    word: "essa",
    translation_ua: "їсти",
    translation_en: "to eat",
    translation_de: "essen",
    audioSrc: "/audio/11/essa.mp3",
  },
  {
    key: "11-18",
    region: 11,
    id: 18,
    word: "trinka",
    translation_ua: "пити",
    translation_en: "to drink",
    translation_de: "trinken",
    audioSrc: "/audio/11/trinka.mp3",
  },
  {
    key: "11-19",
    region: 11,
    id: 19,
    word: "Apfl",
    translation_ua: "яблуко",
    translation_en: "apple",
    translation_de: "Apfel",
    audioSrc: "/audio/11/apfl.mp3",
  },
  {
    key: "11-20",
    region: 11,
    id: 20,
    word: "kocha",
    translation_ua: "готувати",
    translation_en: "to cook",
    translation_de: "kochen",
    audioSrc: "/audio/11/kocha.mp3",
  },
  {
    key: "11-21",
    region: 11,
    id: 21,
    word: "Griaß di!",
    translation_ua: "привіт",
    translation_en: "hello",
    translation_de: "Hallo",
    audioSrc: "/audio/11/griass_di.mp3",
  },
  {
    key: "11-22",
    region: 11,
    id: 22,
    word: "Guatn Obnd!",
    translation_ua: "добрий вечір",
    translation_en: "good evening",
    translation_de: "Guten Abend",
    audioSrc: "/audio/11/guatn_obnd.mp3",
  },
  {
    key: "11-23",
    region: 11,
    id: 23,
    word: "Voda",
    translation_ua: "батько",
    translation_en: "father",
    translation_de: "Vater",
    audioSrc: "/audio/11/voda.mp3",
  },
  {
    key: "11-24",
    region: 11,
    id: 24,
    word: "Muada",
    translation_ua: "мати",
    translation_en: "mother",
    translation_de: "Mutter",
    audioSrc: "/audio/11/muada.mp3",
  },
  {
    key: "11-25",
    region: 11,
    id: 25,
    word: "Kinda",
    translation_ua: "діти",
    translation_en: "children",
    translation_de: "Kinder",
    audioSrc: "/audio/11/kinda.mp3",
  },
  {
    key: "11-26",
    region: 11,
    id: 26,
    word: "Bruada",
    translation_ua: "брат",
    translation_en: "brother",
    translation_de: "Bruder",
    audioSrc: "/audio/11/bruada.mp3",
  },
  {
    key: "11-27",
    region: 11,
    id: 27,
    word: "Schwesta",
    translation_ua: "сестра",
    translation_en: "sister",
    translation_de: "Schwester",
    audioSrc: "/audio/11/schwesta.mp3",
  },
  {
    key: "11-28",
    region: 11,
    id: 28,
    word: "Haus",
    translation_ua: "дім",
    translation_en: "house",
    translation_de: "Haus",
    audioSrc: "/audio/11/haus.mp3",
  },
  {
    key: "11-29",
    region: 11,
    id: 29,
    word: "Fensta",
    translation_ua: "вікно",
    translation_en: "window",
    translation_de: "Fenster",
    audioSrc: "/audio/11/fensta.mp3",
  },
  {
    key: "11-30",
    region: 11,
    id: 30,
    word: "Zimma",
    translation_ua: "кімната",
    translation_en: "room",
    translation_de: "Zimmer",
    audioSrc: "/audio/11/zimma.mp3",
  },
  {
    key: "12-1",
    region: 12,
    id: 1,
    word: "Griaß di!",
    translation_ua: "привіт",
    translation_en: "hello",
    translation_de: "Hallo",
    audioSrc: "/audio/12/griass_di.mp3",
  },
  {
    key: "12-2",
    region: 12,
    id: 2,
    word: "Servus!",
    translation_ua: "привіт / бувай",
    translation_en: "hi / bye",
    translation_de: "Servus",
    audioSrc: "/audio/12/servus.mp3",
  },
  {
    key: "12-3",
    region: 12,
    id: 3,
    word: "Pfiat di!",
    translation_ua: "бувай",
    translation_en: "bye",
    translation_de: "Tschüss",
    audioSrc: "/audio/12/pfiat_di.mp3",
  },
  {
    key: "12-4",
    region: 12,
    id: 4,
    word: "Bitte",
    translation_ua: "будь ласка",
    translation_en: "please",
    translation_de: "bitte",
    audioSrc: "/audio/12/bitte.mp3",
  },
  {
    key: "12-5",
    region: 12,
    id: 5,
    word: "Danke",
    translation_ua: "дякую",
    translation_en: "thank you",
    translation_de: "danke",
    audioSrc: "/audio/12/danke.mp3",
  },
  {
    key: "12-6",
    region: 12,
    id: 6,
    word: "Guat",
    translation_ua: "добре",
    translation_en: "good",
    translation_de: "gut",
    audioSrc: "/audio/12/guat.mp3",
  },
  {
    key: "12-7",
    region: 12,
    id: 7,
    word: "Schlecht",
    translation_ua: "погано",
    translation_en: "bad",
    translation_de: "schlecht",
    audioSrc: "/audio/12/schlecht.mp3",
  },
  {
    key: "12-8",
    region: 12,
    id: 8,
    word: "Vül",
    translation_ua: "багато",
    translation_en: "much / many",
    translation_de: "viel",
    audioSrc: "/audio/12/vul.mp3",
  },
  {
    key: "12-9",
    region: 12,
    id: 9,
    word: "Wenig",
    translation_ua: "мало",
    translation_en: "little",
    translation_de: "wenig",
    audioSrc: "/audio/12/wenig.mp3",
  },
  {
    key: "12-10",
    region: 12,
    id: 10,
    word: "Heit",
    translation_ua: "сьогодні",
    translation_en: "today",
    translation_de: "heute",
    audioSrc: "/audio/12/heit.mp3",
  },
  {
    key: "12-11",
    region: 12,
    id: 11,
    word: "Morga",
    translation_ua: "завтра",
    translation_en: "tomorrow",
    translation_de: "morgen",
    audioSrc: "/audio/12/morga.mp3",
  },
  {
    key: "12-12",
    region: 12,
    id: 12,
    word: "Gestan",
    translation_ua: "вчора",
    translation_en: "yesterday",
    translation_de: "gestern",
    audioSrc: "/audio/12/gestan.mp3",
  },
  {
    key: "12-13",
    region: 12,
    id: 13,
    word: "Owa",
    translation_ua: "але",
    translation_en: "but",
    translation_de: "aber",
    audioSrc: "/audio/12/owa.mp3",
  },
  {
    key: "12-14",
    region: 12,
    id: 14,
    word: "Und",
    translation_ua: "і",
    translation_en: "and",
    translation_de: "und",
    audioSrc: "/audio/12/und.mp3",
  },
  {
    key: "12-15",
    region: 12,
    id: 15,
    word: "Oder",
    translation_ua: "або",
    translation_en: "or",
    translation_de: "oder",
    audioSrc: "/audio/12/oder.mp3",
  },
  {
    key: "12-16",
    region: 12,
    id: 16,
    word: "Wo?",
    translation_ua: "де?",
    translation_en: "where?",
    translation_de: "wo?",
    audioSrc: "/audio/12/wo.mp3",
  },
  {
    key: "12-17",
    region: 12,
    id: 17,
    word: "Warum?",
    translation_ua: "чому?",
    translation_en: "why?",
    translation_de: "warum?",
    audioSrc: "/audio/12/warum.mp3",
  },
  {
    key: "12-18",
    region: 12,
    id: 18,
    word: "Wia?",
    translation_ua: "як?",
    translation_en: "how?",
    translation_de: "wie?",
    audioSrc: "/audio/12/wia.mp3",
  },
  {
    key: "12-19",
    region: 12,
    id: 19,
    word: "Jetzt",
    translation_ua: "зараз",
    translation_en: "now",
    translation_de: "jetzt",
    audioSrc: "/audio/12/jetzt.mp3",
  },
  {
    key: "12-20",
    region: 12,
    id: 20,
    word: "Später",
    translation_ua: "пізніше",
    translation_en: "later",
    translation_de: "später",
    audioSrc: "/audio/12/spaeter.mp3",
  },
  {
    key: "13-1",
    region: 13,
    id: 1,
    word: "Bees and honey",
    translation_ua: "гроші",
    translation_en: "money",
    translation_de: "Geld",
    audioSrc: "/audio/13/bees_and_honey.mp3",
  },
  {
    key: "13-2",
    region: 13,
    id: 2,
    word: "Loaf of bread",
    translation_ua: "голова",
    translation_en: "head",
    translation_de: "Kopf",
    audioSrc: "/audio/13/loaf_of_bread.mp3",
  },
  {
    key: "13-3",
    region: 13,
    id: 3,
    word: "China plate",
    translation_ua: "друг",
    translation_en: "friend",
    translation_de: "Freund",
    audioSrc: "/audio/13/china_plate.mp3",
  },
  {
    key: "13-4",
    region: 13,
    id: 4,
    word: "Apples and pears",
    translation_ua: "сходи",
    translation_en: "stairs",
    translation_de: "Treppe",
    audioSrc: "/audio/13/apples_and_pears.mp3",
  },
  {
    key: "13-5",
    region: 13,
    id: 5,
    word: "Barnet (fair)",
    translation_ua: "волосся",
    translation_en: "hair",
    translation_de: "Haar",
    audioSrc: "/audio/13/barnet.mp3",
  },
  {
    key: "13-6",
    region: 13,
    id: 6,
    word: "Bottle and stopper",
    translation_ua: "поліцейський",
    translation_en: "policeman",
    translation_de: "Polizist",
    audioSrc: "/audio/13/bottle_and_stopper.mp3",
  },
  {
    key: "13-7",
    region: 13,
    id: 7,
    word: "Half-inch",
    translation_ua: "украсти",
    translation_en: "to steal",
    translation_de: "stehlen",
    audioSrc: "/audio/13/half-ich.mp3",
  },
  {
    key: "13-8",
    region: 13,
    id: 8,
    word: "Trouble and strife",
    translation_ua: "дружина",
    translation_en: "wife",
    translation_de: "Ehefrau",
    audioSrc: "/audio/13/trouble_and_strife.mp3",
  },
  {
    key: "13-9",
    region: 13,
    id: 9,
    word: "Butcher’s hook",
    translation_ua: "подив / погляд",
    translation_en: "look / glance",
    translation_de: "Blick",
    audioSrc: "/audio/13/butchers_hook.mp3",
  },
  {
    key: "13-10",
    region: 13,
    id: 10,
    word: "Rosie lee",
    translation_ua: "чай",
    translation_en: "tea",
    translation_de: "Tee",
    audioSrc: "/audio/13/rossie_lee.mp3",
  },
  {
    key: "14-1",
    region: 14,
    id: 1,
    word: "Scran",
    translation_ua: "їжа",
    translation_en: "food",
    translation_de: "Essen",
    audioSrc: "/audio/14/scran.mp3",
  },
  {
    key: "14-2",
    region: 14,
    id: 2,
    word: "Kecks",
    translation_ua: "штани",
    translation_en: "trousers",
    translation_de: "Hose",
    audioSrc: "/audio/14/kecks.mp3",
  },
  {
    key: "14-3",
    region: 14,
    id: 3,
    word: "Wool",
    translation_ua: "не місцевий / чужак",
    translation_en: "outsider",
    translation_de: "Außenseiter",
    audioSrc: "/audio/14/wool.mp3",
  },
  {
    key: "14-4",
    region: 14,
    id: 4,
    word: "Jarg",
    translation_ua: "фальшивий / підробка",
    translation_en: "fake / counterfeit",
    translation_de: "falsch / Fälschung",
    audioSrc: "/audio/14/jarg.mp3",
  },
  {
    key: "14-5",
    region: 14,
    id: 5,
    word: "Lid",
    translation_ua: "голова",
    translation_en: "head",
    translation_de: "Kopf",
    audioSrc: "/audio/14/lid.mp3",
  },
  {
    key: "14-6",
    region: 14,
    id: 6,
    word: "La / lad",
    translation_ua: "друг / товариш",
    translation_en: "friend / mate",
    translation_de: "Freund / Kumpel",
    audioSrc: "/audio/14/la.mp3",
  },
  {
    key: "14-7",
    region: 14,
    id: 7,
    word: "Div",
    translation_ua: "дурень",
    translation_en: "fool",
    translation_de: "Narr",
    audioSrc: "/audio/14/div.mp3",
  },
  {
    key: "14-8",
    region: 14,
    id: 8,
    word: "Liddo / little one",
    translation_ua: "дитина",
    translation_en: "child",
    translation_de: "Kind",
    audioSrc: "/audio/14/liddo.mp3",
  },
  {
    key: "14-9",
    region: 14,
    id: 9,
    word: "Bevvy",
    translation_ua: "алкогольний напій",
    translation_en: "alcoholic drink",
    translation_de: "alkoholisches Getränk",
    audioSrc: "/audio/14/bevvy.mp3",
  },
  {
    key: "14-10",
    region: 14,
    id: 10,
    word: "Boss",
    translation_ua: "гарний / чудовий",
    translation_en: "great / awesome",
    translation_de: "toll / großartig",
    audioSrc: "/audio/14/boss.mp3",
  },
  {
    key: "15-1",
    region: 15,
    id: 1,
    word: "Breed",
    translation_ua: "хліб",
    translation_en: "bread",
    translation_de: "Brot",
    audioSrc: "/audio/15/breed.mp3",
  },
  {
    key: "15-2",
    region: 15,
    id: 2,
    word: "Marra",
    translation_ua: "друг / товариш",
    translation_en: "friend / mate",
    translation_de: "Freund / Kumpel",
    audioSrc: "/audio/15/marra.mp3",
  },
  {
    key: "15-3",
    region: 15,
    id: 3,
    word: "Bairn",
    translation_ua: "дитина",
    translation_en: "child",
    translation_de: "Kind",
    audioSrc: "/audio/15/bairn.mp3",
  },
  {
    key: "15-4",
    region: 15,
    id: 4,
    word: "Nappa",
    translation_ua: "голова",
    translation_en: "head",
    translation_de: "Kopf",
    audioSrc: "/audio/15/nappa.mp3",
  },
  {
    key: "15-5",
    region: 15,
    id: 5,
    word: "Toon",
    translation_ua: "місто (особливо Ньюкасл)",
    translation_en: "city (especially Newcastle)",
    translation_de: "Stadt (besonders Newcastle)",
    audioSrc: "/audio/15/toon.mp3",
  },
  {
    key: "15-6",
    region: 15,
    id: 6,
    word: "Clart",
    translation_ua: "бруд",
    translation_en: "mud / dirt",
    translation_de: "Schlamm / Dreck",
    audioSrc: "/audio/15/clart.mp3",
  },
  {
    key: "15-8",
    region: 15,
    id: 8,
    word: "Gadgie",
    translation_ua: "чоловік",
    translation_en: "man",
    translation_de: "Mann",
    audioSrc: "/audio/15/gadgie.mp3",
  },
  {
    key: "15-9",
    region: 15,
    id: 9,
    word: "Gansey",
    translation_ua: "светр",
    translation_en: "sweater",
    translation_de: "Pullover",
    audioSrc: "/audio/15/gansey.mp3",
  },
  {
    key: "15-10",
    region: 15,
    id: 10,
    word: "Radgie",
    translation_ua: "сердитий",
    translation_en: "angry",
    translation_de: "wütend",
    audioSrc: "/audio/15/radgie.mp3",
  },
  {
    key: "15-11",
    region: 15,
    id: 11,
    word: "Spuggy",
    translation_ua: "горобець",
    translation_en: "sparrow",
    translation_de: "Sperling",
    audioSrc: "/audio/15/spuggy.mp3",
  },
  {
    key: "16-1",
    region: 16,
    id: 1,
    word: "Cuddy",
    translation_ua: "кінь",
    translation_en: "horse",
    translation_de: "Pferd",
    audioSrc: "/audio/16/cuddy.mp3",
  },
  {
    key: "16-2",
    region: 16,
    id: 2,
    word: "Pannier",
    translation_ua: "кошик",
    translation_en: "basket",
    translation_de: "Korb",
    audioSrc: "/audio/16/Pannier.mp3",
  },
  {
    key: "16-3",
    region: 16,
    id: 3,
    word: "Garth",
    translation_ua: "сад / двір",
    translation_en: "garden / yard",
    translation_de: "Garten / Hof",
    audioSrc: "/audio/16/Garth.mp3",
  },
  {
    key: "16-4",
    region: 16,
    id: 4,
    word: "Kist",
    translation_ua: "коробка / скриня",
    translation_en: "box / chest",
    translation_de: "Kiste / Truhe",
    audioSrc: "/audio/16/kist.mp3",
  },
  {
    key: "16-5",
    region: 16,
    id: 5,
    word: "Beck",
    translation_ua: "невеликий потік, струмок",
    translation_en: "small stream / brook",
    translation_de: "kleiner Bach",
    audioSrc: "/audio/16/Beck.mp3",
  },
  {
    key: "16-6",
    region: 16,
    id: 6,
    word: "Croft",
    translation_ua: "невелика ферма / ділянка",
    translation_en: "small farm / plot",
    translation_de: "kleiner Bauernhof / Grundstück",
    audioSrc: "/audio/16/Croft.mp3",
  },
  {
    key: "16-7",
    region: 16,
    id: 7,
    word: "Staithe",
    translation_ua: "гавань / причал",
    translation_en: "harbor / quay",
    translation_de: "Hafen / Kai",
    audioSrc: "/audio/16/Staithe.mp3",
  },
  {
    key: "16-8",
    region: 16,
    id: 8,
    word: "Ginnel",
    translation_ua: "вузький прохід / провулок",
    translation_en: "narrow passage / alley",
    translation_de: "enge Gasse / Durchgang",
    audioSrc: "/audio/16/Ginnel.mp3",
  },
  {
    key: "16-9",
    region: 16,
    id: 9,
    word: "Yow",
    translation_ua: "вівця",
    translation_en: "sheep",
    translation_de: "Schaf",
    audioSrc: "/audio/16/Yow.mp3",
  },
  {
    key: "16-10",
    region: 16,
    id: 10,
    word: "Neddy",
    translation_ua: "кінь",
    translation_en: "horse",
    translation_de: "Pferd",
    audioSrc: "/audio/16/Neddy.mp3",
  },
].sort(() => Math.random() - 0.5);


export default async function FlashcardsPage() {
  const userProgress = await getUserProgress();

  const hasProgress = !!userProgress?.activeRegion;

  return (
    <div className="flex flex-row-reverse gap-12 px-6 py-8">
      <StickyWrapper>
        {userProgress && (
          <>
            <UserProgress
              activeCourse={userProgress.activeRegion}
              hearts={userProgress.hearts}
              points={userProgress.points}
            />
            <Quests points={userProgress.points} />
            {userProgress.activeRegion && (
              <RegionImage activeRegionId={userProgress.activeRegion.id} />
            )}
          </>
        )}
        <Feedback />
      </StickyWrapper>

      <FeedWrapper>
        <FlashcardsPracticeClient
          flashcards={flashcards}
          hasProgress={hasProgress}
        />
      </FeedWrapper>
    </div>
  );
}
