// app/layout.tsx
import type { Metadata } from "next";
import { Baloo_2 } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs';
import { Toaster } from "sonner";
import { PracticeModal } from "@/components/modals/practice-modal";
import { HeartsModal } from "@/components/modals/hearts-modal";
import { ExitModal } from "@/components/modals/exit-modal"
import { ukUA } from "@clerk/localizations";
import { LanguageProvider } from "@/components/languageContext";

const font = Baloo_2({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ua">
      <body className={font.className}>
        <ClerkProvider localization={ukUA}>
          <LanguageProvider>
            <Toaster />
            <ExitModal />
            <HeartsModal />
            {/* <PracticeModal /> */}
            {children}
          </LanguageProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
